### ISSUE TITLE
apt remove php8* doesn't work.

### ISSUE THREAD

**Issue by reichenbach001** [Alirezad07/X-Panel-SSH-User-Management#130]
سلام
وقتت بخیر و مرسی که زحمت کشیدی این پنل رو درست کردی.
توی اسکریپت نصب یه جا هست که اسکریپت سعی می‌کنه ورژن ۸ پی‌اچ‌پی رو در صورت وجو پاک کنه که دستورش کار نمی‌کنه:
apt remove php8*

اراداتمند

**Comment by Alirezad07** [comment]
درود 
در این مدت به قدری درگیر یکسری مسائل دگ بودیم که اصلاح این موارد انجام ندادیم
