### ISSUE TITLE
مشکل در اجرا برخی دستورات

### ISSUE THREAD

**Issue by Sadraka** [Alirezad07/X-Panel-SSH-User-Management#2]
سلام خسته نباشید 

بک اپ گیری و بن کردن کردن ایپی و محدودیت کاربران اعمال نمیشه و اصلا Tag input که قرار دادی فرقی نمی کنه و روی غیر فعال میمونه این قابلیت ها نسخه پرو داره برای شما یا رو این نسخه باید اجرا بشه 
 ubunut 22

**Comment by mna200922122** [comment]
سلام خسته نباشید 
مهم تزین قسمت نشون دادن حجم استفاده شده کاربره که برا من فعال نیست

**Comment by Alirezad07** [comment]
طی چند روز آینده تمامی باگ ها رفع میشن

**Comment by Sadraka** [comment]
تشکر

**Comment by Sadraka** [comment]
فقط ریسپانسیو سایت هم مشکل داره اگه وقتتون کم بود و کمکی چیزی تو قسمت طراحیش خواستید بگید

**Comment by Alirezad07** [comment]
بله رو نسخه موبایل مشکلاتی داره. عزیز دلی چشم حتما.
بروزرسانی کنید برخی باگ های اصلی رفع شدند که برای نمایش حجم مصرفی بوده

**Comment by saeedtntt** [comment]
اگر امکان مولتی پورت هم اضاف بشه عالیه ، ممنون

**Comment by Sadraka** [comment]
سلام خسته نباشید 
همچنان قسمت محدودیت کاربر و بلاک ایپی ایران برای من غیر فعاله و فعال نمیشه حجم مصرفی رو هم نشون نمیده

**Comment by Alirezad07** [comment]
> سلام خسته نباشید همچنان قسمت محدودیت کاربر و بلاک ایپی ایران برای من غیر فعاله و فعال نمیشه حجم مصرفی رو هم نشون نمیده

سلام بلاک ip ایران یکسری مشکلات داره که باید رفع بشه پنل خیلی با عجله راه اندازی شد که نیاز دوستان برطرف بشه کمی زمان میبره تا ایرادات رفع بشن

**Comment by Alirezad07** [comment]
حجم مصرفی نباید مشکلی داشته باشه پنل بروز کنید

**Comment by Sadraka** [comment]
سلام بله بازمم ممنون بابت وقتی که میزارید منم خواستم برخی مشکلات بگم

**Comment by Sadraka** [comment]
درباره محدودیت کاربر همون طور که میبینید برای من فعال نمیشه 

![Untitled](https://user-images.githubusercontent.com/68942983/235109161-c51f992e-b892-454d-89b8-d13e3f2760fb.jpg)
حجم مصرفی هم همون طور که میبینید روی 5 مگ تنظیم کردم ولی من بیشتر از اون مصرف کردم باز هم نه اینجا ثبت شده نه اکانت محدود شده 
![1](https://user-images.githubusercontent.com/68942983/235109402-77c56358-861c-4e4b-8cdf-98a4b893e98f.jpg)

**Comment by mymish** [comment]
سلام و عرض ادب
تشکر از امکاناتی که در اختیار گذاشتید.
پنل دکمه خروج ندارد، در صورت امکان اضافه نمایید.
دو کاربر همزمان متصل می شوند.

**Comment by Alirezad07** [comment]
> سلام.روی منوی تنظیمات میرم پانل هنگ میکنه و مجبورم دوباره دستور نصب بزنم

نسخه جدید نصب کنید
