### ISSUE TITLE
 بازم عدم شمارش 

### ISSUE THREAD

**Issue by gachineh** [Alirezad07/X-Panel-SSH-User-Management#206]
ساعت پنج عصر ۲۶ خرداد فایل ۳.۳ رو آپدیت کردید و منم نصب کردم
ip:port/reinstall این رو هم زدم
ساکسز داد
ولی باااز هم ترافیکارو نمیشماره و مشتریام دارن همچنان رایگان استفاده میکنن...

**Comment by Alirezad07** [comment]
> ساعت پنج عصر ۲۶ خرداد فایل ۳.۳ رو آپدیت کردید و منم نصب کردم ip:port/reinstall این رو هم زدم ساکسز داد ولی باااز هم ترافیکارو نمیشماره و مشتریام دارن همچنان رایگان استفاده میکنن...

مشکل از سمت پنل نیست سرور خودتون چک کنید که پنل را به درستی اجرا کنید
