### ISSUE TITLE
بعد اپدیت بالا نمیاد

### ISSUE THREAD

**Issue by mahdigoli** [Alirezad07/X-Panel-SSH-User-Management#228]
سلام من ورژن 2.4 نصب هست وقتی که نصب کردم ورژن جدید رو دیگه بالا نمیاد اون ip:port/reinstall هم اوکی کردم ولی بازن نمیاد

5.9.161.52 is currently unable to handle this request.

HTTP ERROR 500

**Comment by lonel1370** [comment]
سلام تو سایت کلودفلر cdn فعال کردی؟ ابر رو روشن کردی؟
