### ISSUE TITLE
Please update the code as open source

### ISSUE THREAD

**Issue by samsesh** [Alirezad07/X-Panel-SSH-User-Management#26]
Please upload the entire code as an open source document on GitHub so that other developers can help develop and solve problems by creating pull requests.

**Comment by cr4zyfish** [comment]
What do you mean? its opensource. which part is closed source?

**Comment by samsesh** [comment]
Put the PHP code and all parts except installation on GitHub instead of release, just so that the ability to contribute and develop in a better way.

**Comment by WatchDogsDev** [comment]
I think this is very important because of Github policies and also it is required for contributors to help improving the project.

**Comment by samsesh** [comment]
added on commit 64d07f1e02373c1ff163959ab547b511c6acc235
