### ISSUE TITLE
DO NOT INSTALL THIS APP 

### ISSUE THREAD

**Issue by somedeveloper00** [Alirezad07/X-Panel-SSH-User-Management#280]
It's a malware for DDOS attacks. UNINSTALLING IS NOT SUFFICIENT; you must reinstall your servers

**Comment by somedeveloper00** [comment]
this is according to the warning email from VPS2Day tech support team. They've been doing this for years and are trustworthy; 
![image](https://github.com/Alirezad07/X-Panel-SSH-User-Management/assets/79690923/62b26189-e87c-42ef-bf5b-48786794e139)

**Comment by sherman2000** [comment]
![Uploading Screenshot_2023-07-06_21-43-41.jpg…]()

**Comment by Mahdar62** [comment]
سلام از نظر دوستان بهتره از چه پروژه ای استفاده کنیم؟

**Comment by somedeveloper00** [comment]
برنامه مشابه NekoBox برای اندروید و NetMod برای ویندوز پیشنهاد میکنم. البته NetMod اوپن سورس نیست و یوزر هاش هم زیاد نیست، پس حواستون باشه، ولی NekoBox کاملا مطمئنه
