### ISSUE TITLE
چطوری آپدیت کنیم پنل رو

### ISSUE THREAD

**Issue by RmnJL** [Alirezad07/X-Panel-SSH-User-Management#282]
هرچی نصب میکنم ورژن 3.5 رو انتخاب میکنم بازم پنل 3.4 میمونه

ممنون میشم راهنمایی کنید

**Comment by majiuz** [comment]
سلام من هم این مشکلو دارم

**Comment by amirict** [comment]
من آپدیت کردم پنلم باز نمیشه دیگه
مجبور شدم مجدد نصب کنم حالا دیگه SSL فعال نمیشه
:(((((((

**Comment by sizadbakhsh** [comment]
سلام وقت بخیر
نه آپدیت نمیشه
یه بخش مشکل داره
علیرضا یادش رفته اونو اصلاح کنه
توی کدهاش دیدم
باید 34 رو میکرده 35 که نکرده و پکیج آپدیت جدید رو نمیگیره
