### ISSUE TITLE
کار نکردن پنل

### ISSUE THREAD

**Issue by mrmasiha0** [Alirezad07/X-Panel-SSH-User-Management#283]
سلام من روی سرور جدید پنل رو نصب کردم. یوزر و پسورد ادمین رو که می زنم وارد نمیشه. 2 باره هم نصب کردم ولی بازم همین مشکل رو داره.ممنون میشم اگر راهنمایی کنید.

**Comment by majiuz** [comment]
ip:port/reinstall
حتما چه نصب مجدد انجام دادید یا برنامرو روی سرور جدید اجرا کردید بعد از نصب اینکارو بکنید درست میشه

**Comment by mrmasiha0** [comment]
درست شد.ممنونم
