### ISSUE TITLE
مشکل مصرف زیاد سی پی یو در نسخه 3.5

### ISSUE THREAD

**Issue by randomguy-on-internet** [Alirezad07/X-Panel-SSH-User-Management#285]
سلام من 10 تا کاربر کلا دارم و وقتی کلا دو نفر متصل بودن مصرف cpu اینجوریه.

![Screenshot_1](https://github.com/Alirezad07/X-Panel-SSH-User-Management/assets/79375739/a2097d18-77bb-448e-8c80-9f8a0ba722db)

**Comment by sherman2000** [comment]
اسکریپت کار برادران زحمت کش سپاه از منابع سرور جهت دی داس و ... به سرورهای امریکایی استفاده می کند استفاده نکنید

**Comment by randomguy-on-internet** [comment]
> اسکریپت کار برادران زحمت کش سپاه از منابع سرور جهت دی داس و ... به سرورهای امریکایی استفاده می کند استفاده نکنید

شما خودت اگر سواردت به درک و فهم کد نمیرسه نیازی به جواب دادن به ایشو های بقیه نداری. نظراتت رو بنویس روی یه کارتن و لوله کن و فرو کن به خودت.
مرسی.

**Comment by sherman2000** [comment]
از یه بسیجی سطح پایین ادبیات بهتری انتظار نمیره فرو که اقا کرده لذتش ببر برادر

**Comment by randomguy-on-internet** [comment]
پسر خوب فرو کن تو حلقت که صدات بند بیاد، فرو کردی پایین دوباره فشار اومده
بهت کامنت گذاشتی.
اگر هم از جای دیگه فشار میخوری بگو شاید بتونم یکیو پیدا کنم کمکت کنه.
