### ISSUE TITLE
اتک سمت سرورها و مشکل امنیتی اسکریپت

### ISSUE THREAD

**Issue by sizadbakhsh** [Alirezad07/X-Panel-SSH-User-Management#289]
با سلام و وقت بخیر
علیرضا جان تمام سرورهای خودم و دوستان که از پنل شما استفاده میکردن مثل آب خوردن هک شدن و مشکل از سمت اسکریپت متاسفانه
کاش بتونی توضیحی بابت این موضوع داشته باشی

**Comment by AliROCK66** [comment]
کلا ارتباط ssh امنیت چندانی برای vpn نداره هر پنل ssh دیگه هم بزنید همین میشه
