### ISSUE TITLE
وصل نشدن کاربر 

### ISSUE THREAD

**Issue by Pejman-Parsian** [Alirezad07/X-Panel-SSH-User-Management#29]
با درود و سپاس فراوان از برنامه عالی شما. برنامه بر روی سرور نسب شده ولی کاربر با برنامه NapsternetV نمیتواند متصل شود. سپاسگذار میشوم اگر راهنمایی کنید که این مشکل را برطرف کنم.

**Comment by Alirezad07** [comment]
بررسی کنید سرور فیلتر نباشد

**Comment by Pejman-Parsian** [comment]
دوست عزیز، این مشکل فقط روی سرور Vultr هست. روی سرورهای دیگر این مشکل وجود ندارد. بنابراین این تیکت رو میبندم. باز هم سپاس از زحمات شما.

**Comment by Alirezad07** [comment]
اگر براتون ممکن هست از طریق کانال تلگرامی به ادمین پیام دهید تا بررسی کند.
