### ISSUE TITLE
Bug: ip resolve error 403

### ISSUE THREAD

**Issue by Deihim007** [Alirezad07/X-Panel-SSH-User-Management#325]
Hello,
First of all, I'd like to thank you for all your efforts.
I've been watching this repo grow from its early stages.
You did a great job developing this project, I know it's not easy to develop a non-profit open-source project. (especially when you are being criticized instead of being praised)

While updating to the new version I ran into a bug that seems to be an external problem, Which I guess can happen to anyone due to the nature of the project.
```
-------- Connection Details -----------
IP :
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/ip</code> from this server.</h2>
<h2></h2>
</body></html>
```
This is not a critical bug for installation but if you try to use the SSL script it'll fail because it can't match the IP address to the domain.
I suggest doing an internal check like reading the main network interface IP address or asking for the IP address manually as a fallback.

**Comment by Alirezad07** [comment]
> Hello, First of all, I'd like to thank you for all your efforts. I've been watching this repo grow from its early stages. You did a great job developing this project, I know it's not easy to develop a non-profit open-source project. (especially when you are being criticized instead of being praised)
> 
> While updating to the new version I ran into a bug that seems to be an external problem, Which I guess can happen to anyone due to the nature of the project.
> 
> ```
> -------- Connection Details -----------
> IP :
> <html><head>
> <meta http-equiv="content-type" content="text/html;charset=utf-8">
> <title>403 Forbidden</title>
> </head>
> <body text=#000000 bgcolor=#ffffff>
> <h1>Error: Forbidden</h1>
> <h2>Your client does not have permission to get URL <code>/ip</code> from this server.</h2>
> <h2></h2>
> </body></html>
> ```
> 
> This is not a critical bug for installation but if you try to use the SSL script it'll fail because it can't match the IP address to the domain. I suggest doing an internal check like reading the main network interface IP address or asking for the IP address manually as a fallback.

Hello
Thank you for your kindness and love.
The project is under development and the version of Laravel XPanel is supposed to be released in the next 10 days.
The error you sent is related to your server's lack of access to the https://ipinfo.io/ip domain, and that is why it gives an error.
This error causes cron job panel to be disturbed. If it is for personal use, it is not important and wait for the new version to be released in the next few days. But if it is not personal, be sure to correct the cron job.

**Comment by Deihim007** [comment]
Looking forward to it 👍 
Best wishes <3
