### ISSUE TITLE
مواردی که در نسخه ۳.۴ عالی کار میکردند و در نسخه جدید از کار افتاده

### ISSUE THREAD

**Issue by mrnet2023** [Alirezad07/X-Panel-SSH-User-Management#340]
با سلام اول تشکر میکنم از اقای علیرضای عزیز همین که وقت میذاری و رو چنین پنلی کار میکنی ممنونم ازت 

علیرضا جان خواهش میکنم ازت تو اپدیت هایی که انجام میدیید اون مواردی که مشگل نداره رو تغییر ندید الان رو نسخه جدید مشکلانی که رو نسخه قبل نبود بوجود اومده 
یکی در صفحه پیشخوان انلاین ها غیر فعال شده
دومین مشگل عدم فعال شدن بلاکip های ایران هست که در نسخه قبل فعال میشد ظاهرا لینک به مشکل خورده چون بعد نصب بسته میگه چنین پوشه ای موجود نیست
....
سومین مشکل عدم نشان دادن حجم مصرفی هست
...
مشکل بعدی موقع ساخت یوزر هست که تاریخ انقضا با اولین اتصال از کار افتاده درصورتی که همه این موارد در نسخه قبل کامل کار میکردن
.....
 ارتباط یوزرها مولتی یوزر شده و اعمال محدودیت تعداد یوزر از کار افتاده با بروزرسانی نسخه اخر کل سرویس های پنل یه جورایی نابود شده

لطفا تا قبل از از بین رفتن باگ ها لیست ورژن های قبل رو هنگام نصب حذف نکنید الان مجبوریم اخرین ورژن رو نصب کنیم در صورتی که ورژن ۳.۴ بدون مشکل بود یا لا اقل این مشکلاتی که گفتمو نداشت متشکرم از زحماتت موفق باشی

**Comment by mehdi7766** [comment]
یه مشکل دیگه هم داره که اونم مدیر تعریف میکنی و با یوزر مدیر وارد میشی وارد صفحه کاربران نمیشه

**Comment by merikh11** [comment]
درود علیرضای عزیز 
داداش چرا امکانات عالی مث بلاک ای پی و وردپرسو ورداشتی از پنل ؟؟؟؟؟؟

لطفا اگر امکانش هست اضافشون کن عالی بودن

**Comment by mrnet2023** [comment]
دوستان بلاک ip ایران رو این اسکریپت فول نیست ولی فعلا بدنیست تا مشکل پنل حل بشه نصب کنید 
bash <(curl -s https://raw.githubusercontent.com/elemen3/wepn/master/wepn.sh)
من چک‌کردم لینک بلاکip پنل از دسترس خارج شده دلیل فعال نشدنش همین هست

**Comment by mo0ry** [comment]
با همین فایل و دستور ورژن 3.4 نصب کنید دوباره

bash /root/install.sh
[install.zip](https://github.com/Alirezad07/X-Panel-SSH-User-Management/files/12062045/install.zip)

**Comment by mo0ry** [comment]
> یه مشکل دیگه هم داره که اونم مدیر تعریف میکنی و با یوزر مدیر وارد میشی وارد صفحه کاربران نمیشه

به نظرم پروژه باید به صورت عمومی و اختصاصی باید ارائه بشه تا کسی رایگان دریافت کرد طلب کار نشه

**Comment by rapomid** [comment]
سلام من نسخه جدید 3.6 نسب کردم

خیلی باگ داره

چجوری دوباره نسخه 3.4  نصب کنم

نسخه 3.6 
حجم مصرفی رو نشون نمیده
محدودیت ترافیک نداره .. مثلا  دو مگ با 200 گیگ هی فرقی نداره و همه نامحدود حساب میشن

**Comment by mo0ry** [comment]
> سلام من نسخه جدید 3.6 نسب کردم
> 
> خیلی باگ داره
> 
> چجوری دوباره نسخه 3.4 نصب کنم
> 
> نسخه 3.6 حجم مصرفی رو نشون نمیده محدودیت ترافیک نداره .. مثلا دو مگ با 200 گیگ هی فرقی نداره و همه نامحدود حساب میشن

https://github.com/Alirezad07/X-Panel-SSH-User-Management/issues/340#issuecomment-1636807777

**Comment by rapomid** [comment]
پنل بالا نمیاد

**Comment by rapomid** [comment]
دادا یه دستور بزار که 3.4  رو نصب کنم ممنون

**Comment by mehdi7766** [comment]
با تشکر از Mo0ry 3.4 رو نصب کردم اوکی هم بود

**Comment by mrnet2023** [comment]
سلام تونستی بلاکip ایران رو فعال کنی بعد نصب؟

**Comment by mrnet2023** [comment]
Mo0ry 
داداش دمت گرم
دادا یه زحمتی میکشی من بررسی که کررم دیدم در قسمت بلاکip دلیل فعال نشدنش این بود که لینک اصلی از دسترس خارج شده بود ببسن میتونی ایرادشو پیدا کنی بتونیم بلاک ip رو فعلا فعال کنیم رو نسخه ۳.۴ تا اپدیت جدید اماده بشه
https://raw.githubusercontent.com/Alirezad07/X-Panel-SSH-User-Management/main/block_iran.sh --ipv4)

**Comment by mo0ry** [comment]
> سلام تونستی بلاکip ایران رو فعال کنی بعد نصب؟

اول این فایل رو بساز بعدش اجرار کن
bash /root/block_iran.sh
```

#!/bin/sh
sudo apt-get install curl unzip perl
sudo apt-get install xtables-addons-common -y
sudo apt-get install libtext-csv-xs-perl libmoosex-types-netaddr-ip-perl -y
wait
sudo mkdir /usr/share/xt_geoip
chmod 777 /usr/lib/xtables-addons/xt_geoip_build
wait
MON=$(date +"%m")
YR=$(date +"%Y")

wget https://download.db-ip.com/free/dbip-country-lite-${YR}-${MON}.csv.gz
cp dbip-country-lite-${YR}-${MON}.csv.gz /usr/share/xt_geoip/
rm dbip-country-lite-${YR}-${MON}.csv.gz
gunzip /usr/share/xt_geoip/dbip-country-lite-${YR}-${MON}.csv.gz
/usr/lib/xtables-addons/xt_geoip_build -D /usr/share/xt_geoip/ -S /usr/share/xt_geoip/
modprobe xt_geoip
lsmod | grep ^xt_geoip
wait
echo -e "\n Download Success GEOIP Library  \n"
```

bash /root/block_iran.sh

**Comment by mrnet2023** [comment]
You have no un
[Code](https://github.com/Alirezad07/X-Panel-SSH-User-Management)
Issues
261
[Pull requests](https://github.com/Alirezad07/X-Panel-SSH-User-Management/pulls)
[Discussions](https://github.com/Alirezad07/X-Panel-SSH-User-Management/discussions)
[Actions](https://github.com/Alirezad07/X-Panel-SSH-User-Management/actions)
[Projects](https://github.com/Alirezad07/X-Panel-SSH-User-Management/projects)
[Security](https://github.com/Alirezad07/X-Panel-SSH-User-Management/security)
[Insights](https://github.com/Alirezad07/X-Panel-SSH-User-Management/pulse)
[Jump to bottom](https://github.com/Alirezad07/X-Panel-SSH-User-Management/issues/340#issue-comment-box)
مواردی که در نسخه ۳.۴ عالی کار میکردند و در نسخه جدید از کار افتاده #340
Open
[mrnet2023](https://github.com/mrnet2023) opened this

**Comment by mrnet2023** [comment]
Mo0ry
جان داداشم ممنونم ازت زحمت کشیدی
الان این دستورات میتونه کامل سرورهای ایران و دامینهاشو بلاک‌کنه؟
سوال مم بابت اینه که چون من قبلا دستور دیگه ای زدم و الان این دستورو اعمال کردم تغییر نکرد احتمال میدم اونی که خودم نصب گردم نمیذاره کدی که شما زدید فعال بشه درست حالا ا نی که رو پنل علیرضا فعال کرده بود عالی ریشه ای میبست سرور های داخلی رو
