### ISSUE TITLE
مشکلات امنیتی 

### ISSUE THREAD

**Issue by mehrankmlf** [Alirezad07/X-Panel-SSH-User-Management#348]
سلام پنل یه شدت دارای مشکلات امنیتی هست . به راحتی هک و vps از سمت دیتا سنتر مسدود میشه .

**Comment by amirict** [comment]
شما نصب نکن.

**Comment by Alirezad07** [comment]
> سلام پنل یه شدت دارای مشکلات امنیتی هست . به راحتی هک و vps از سمت دیتا سنتر مسدود میشه .

درود لطفا مشکلات بفرمائید که رفع کنم
