### ISSUE TITLE
christmas?!

### ISSUE THREAD

**Issue by cr4zyfish** [Alirezad07/X-Panel-SSH-User-Management#39]
چرا اولین کاربر رو که ایجاد می کنیم توی قسمت اسم نوشته christmas ؟؟!

در ضمن این دو قابلیت هم به نظرم برای شناسایی نشدن پنل:

امکان تعریف url اختصاصی و اگر کسی بدون داشتن url اختصاصی از پورتی که پنل روش هست بازدید کنه خطای not found آپاچی نمایش داده بشه یا کلا محدودیت IP برای دسترسی به پنل ایجاد بشه.

قسمت انتخاب تاریخ انقضا هم به فرمت آمریکایی هست و جالب نیست بهتره به صورت yyyy-mm-dd باشه

+یک پنل برای کاربران که بتونن پسورد رو تغییر بدن.

+آدرس با کارمزد شبکه پایین برای دونیت

**Comment by Alirezad07** [comment]
پنل حتما روی ابونتو نصب کنید از نسخه 18 تا 22 تست شده است.
برای پنل پورت اختصاصی قرار دادیم که هرکس می تواند پورت دلخواه بگذارد.
در مورد تاریخ که فرمودید از ابتدای پنل با این فرمت بوده و تغییر دادن این مورد باعث آسیب به دیتا می شود.
این پنل برای مدیریت SSH ات برای مورد پنل که کاربر بتواند تغییر کلمه عبور بزند در آینده API اضافه خواهد شد تا کاربر بتواند ربات شخصی خودش را طراحی کند.
در مورد دونیت هم چشم شبکه ای با کارمز پائین قرار خواهیم داد.

**Comment by cr4zyfish** [comment]
روی اوبونتو 22 نصب هست. منظورم اینه در شکل زیر:

![f](https://github.com/Alirezad07/X-Panel-SSH-User-Management/assets/90797624/e1a076a4-ce8f-4414-8df6-0280fc2f0bf4)

کاربر اولی اسمش یک چیز دیگه هست ولی نشون میده christmas یعنی چنین کاربری در ssh ایجاد نشده ولی این رو می نویسه.
پنل های دیگه یک قابلیت قرار میدن که پنل مثلا فقط از آدرس http://ip:12345/custom در دسترس باشه و وقتی کسی به http://ip:12345 مراجعه کنه متوجه نشه پنل نصب هست. ( جلوگیری از active probing )

**Comment by cr4zyfish** [comment]
به خاطر نصب پنل چینی v2ray روی سرور و فعال بودن گوگل ترنسلیت روی مرورگر بود!
