### ISSUE TITLE
نحوه بک اپ از یوزر ها ؟ و کلاینت ios 

### ISSUE THREAD

**Issue by megasoheilsh** [Alirezad07/X-Panel-SSH-User-Management#46]
سلام کلاینت مناسب برای ios چی هستش؟ 
واینکه نحوه بک اپ یوزر ها و ریستور به چه صورته؟

**Comment by Alirezad07** [comment]
napsternetv
از بخش تنظیمات گزینه بکاپ و رستور

**Comment by megasoheilsh** [comment]
با تشکر از شما دیدم

**Comment by megasoheilsh** [comment]
کاربرد مولتی سرور چیه؟

**Comment by Alirezad07** [comment]
مولتی سرور فعلا راه اندازی نشده است
