### ISSUE TITLE
کلاینت پیشنهادی برای ویندوز؟ 

### ISSUE THREAD

**Issue by megasoheilsh** [Alirezad07/X-Panel-SSH-User-Management#53]
سلام برای ویندوز چه کلاینتی پیشنهاد میدین؟ netmod مشکل روشن شدن کانکشن داره

**Comment by hamed00019** [comment]
مشکل روشن شدن کانکشن یعنی چی؟
netmode به درستی داره کار میکنه

**Comment by AghaKazem** [comment]
به نظرم این روش کارتون رو راه میندازه:
https://youtu.be/7oCOjLhzq6Q

**Comment by AghaKazem** [comment]
به نظرم این روش کارتون رو راه میندازه:
https://youtu.be/7oCOjLhzq6Q

**Comment by ssmetall** [comment]
مشکل حل شد ، در ویندوز گزینه use ssh رو باید میزدم و بعد استارت میکردم
