### ISSUE TITLE
دستی بکاپ گرفتن (از طریق ترمینال)

### ISSUE THREAD

**Issue by mgh2010** [Alirezad07/X-Panel-SSH-User-Management#98]
سلام خسته نباشید
دمت گم برای پنل عالی تون.
من توی سرور به مشکل خوردم. پنل موقع بالا آمدن تو لوگین **ارورر 500** میده.
خواستم ببینم چه طوری میتونم دستی از طریق ترمینال از کاربرا بک آپ بگیرم؟؟ که بتونم رسیت کنم کلن سرور رو
تشکر

**Comment by mgh2010** [comment]
اگه بشه کدی که سمت پنل برای بک آپ گیری استفاده میشه هم تو ترمینال دستی بزنیم کار راه میوفته؟؟؟
الان هیچ دسترسی به پنل نداریم

**Comment by rezaziyai** [comment]
مهندس مجدد پنل رو نصب کن کاربر ها حذف نمیشن 
آپاچی نصب باشه همچنین سرورت آپدیت باشه حل میشه ارورت پورت رو موقع نصب مجدد پیشفرض بذار

**Comment by mgh2010** [comment]
> مهندس مجدد پنل رو نصب کن کاربر ها حذف نمیشن آپاچی نصب باشه همچنین سرورت آپدیت باشه حل میشه ارورت پورت رو موقع نصب مجدد پیشفرض بذار

سلام. والا کلن پاک کردن و از اول نصب کردم ولی حل نشد. مثل اینکه باگ خورده باید یه ریست کلی کنم. فقط نیازه که این کاربرا ها رو بک آپش رو داشته باشم بشه ریستوری کرد.
توی سرور هم با دستور `find /root -name "*.sql" -type f` سرچ کردم برای پیدا کردن دیتا بیس پنل ولی مثل اینکه با فرمتی دیگه مهندس ذخیره کردن. وقتش رو داشتم برسی میکردم کد ها رو ببینم چی به چیه..

**Comment by mgh2010** [comment]
`mysqldump -u 'DB_USER' --password='DB_PASS' XPanel > /var/www/html/cp/storage/backup/XPanel-backup.sql`

دستورش ظاهرن اینه ولی سرورم مشکل داره اصن دستا بیس ران نمیشه...

![Screenshot 2023-05-21 214939](https://github.com/Alirezad07/X-Panel-SSH-User-Management/assets/55698586/44467698-d813-4088-9099-b629dff3f765)

**Comment by mgh2010** [comment]
مشکل برطرف شد. حجم سرور کم بود. ارتقا دادم الان دیتا بیس ران میشه و پنل هم بالا آمد!
